### ISSUE TITLE
Chrome Drivers Issue in Kali

### ISSUE THREAD

**Issue by Deathpoolxrs** [netsquare/BrowserBruter#6]
Traceback (most recent call last):
  File "/home/kali/Desktop/WAPT/BrowserBruter/BrowserBruter.py", line 638, in get_and_initialize_chrome_driver
    driver = Chrome(executable_path="res/chrome/chromedriver", version_main=122, options=options, retries=max_retry, seleniumwire_options={'proxy': {'http': args.proxy, 'https': args.proxy}} if args.proxy else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 378, in __init__
    raise FileNotFoundError(
FileNotFoundError: 
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the `browser_executable_path='/path/to/browser/executable` parameter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/WAPT/BrowserBruter/BrowserBruter.py", line 647, in get_and_initialize_chrome_driver
    driver = Chrome(executable_path="res/chrome/chromedriver", version_main=122, options=options, retries=max_retry, seleniumwire_options={'proxy': {'http': args.proxy, 'https': args.proxy}} if args.proxy else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 378, in __init__
    raise FileNotFoundError(
FileNotFoundError: 
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the `browser_executable_path='/path/to/browser/executable` parameter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/WAPT/BrowserBruter/BrowserBruter.py", line 656, in get_and_initialize_chrome_driver
    driver = Chrome(executable_path="res/chrome/chromedriver", version_main=122, options=options, retries=max_retry, seleniumwire_options={'proxy': {'http': args.proxy, 'https': args.proxy}} if args.proxy else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 378, in __init__
    raise FileNotFoundError(
FileNotFoundError: 
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the `browser_executable_path='/path/to/browser/executable` parameter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/WAPT/BrowserBruter/BrowserBruter.py", line 1261, in run_browser_instance
    driver = get_and_initialize_chrome_driver()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/WAPT/BrowserBruter/BrowserBruter.py", line 664, in get_and_initialize_chrome_driver
    driver = Chrome(executable_path="res/chrome/chromedriver", version_main=122, options=options, seleniumwire_options={'proxy': {'http': args.proxy, 'https': args.proxy}} if args.proxy else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/Desktop/WAPT/BrowserBruter/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 378, in __init__
    raise FileNotFoundError(
FileNotFoundError: 
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the `browser_executable_path='/path/to/browser/executable` parameter.

**Comment by Deathpoolxrs** [comment]
My mistake, I cloned the repo rather than downloading the release zip. repo dont have chrome drivers under res/ folder.

**Comment by zinja-coder** [comment]
@Deathpoolxrs Glad you found it. Have a nice day hacker x)
